### ISSUE TITLE
autoloader vs include

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [phingofficial/task-svn#1]
After commit https://github.com/phingofficial/task-svn/commit/78830e6421c999c69defe22d30c7a4b48a5fb586#diff-1b0c42684ad29fdbbb2c53186efc33b0c210b6c9eda945dadf1f05794864f33bL72 svn-tasks corrupted:

[PHP Error] Use of undefined constant VERSIONCONTROL_SVN_FETCHMODE_ASSOC - assumed 'VERSIONCONTROL_SVN_FETCHMODE_ASSOC' (this will throw an Error in a future version of PHP) [line 79 of phar:///home/me/bin/phing.phar/vendor/phing/task-svn/src/SvnBaseTask.php]

**Comment by siad007** [comment]
@MiRacLe-RPZ thx for the report - fixed in https://github.com/phingofficial/task-svn/commit/1369d8cb67f76c3ea690b97623e2ae078a782402
