### ISSUE TITLE
svn tasks broken inside phing.phar

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [phingofficial/task-svn#2]
[PHP Error] include_once(/SVN/Command/Update.php): failed to open stream: No such file or directory [line 263 of phar:///home/me/bin/phing-3.0.0-RC1.phar/vendor/pear/versioncontrol_svn/VersionControl/SVN.php]
[PHP Error] include_once(): Failed opening '/SVN/Command/Update.php' for inclusion...

phing-3.0.0-RC1.phar/vendor/pear/versioncontrol_svn/VersionControl/SVN.php:263
```
        if (include_once realpath(dirname(__FILE__)) . "/SVN/Command/{$cmd}.php") { 
```

**Comment by MiRacLe-RPZ** [comment]
P.S.
as workaround i use `<includepath classpath="${my-build-env}/vendor/pear/versioncontrol_svn/" mode="prepend" />` ...

**Comment by mrook** [comment]
Fixed in https://github.com/phingofficial/task-svn/commit/c7672dd768cd88eef2c721196afac518a6574a13, will be packaged into the next version of the phar.
